Repository netobserv/network-observability-operator, pull requests merged in 2021-11, with the labels that each got.

#12 Fix goflow-kube deployment - works with configmap
  config/rbac/role.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowcollector_controller.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
Labels: lgtm

#15 NETOBSERV-82: Enforcing crd validation to only have one instance per cluster
  config/crd/kustomization.yaml
  config/crd/patches/singleton_in_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
Labels: lgtm, approved

#16 [NETOBSERV-34] [NETOBSERV-87] ConfigMap fields
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flowcollector_controller.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
Labels: lgtm, approved

#17 Improve documentation
  README.md
  config/manager/manager.yaml
  config/samples/net-cluster-patch.json
Labels: lgtm, approved

#18 Add vendors in Dockerfile and avoid mod download
  Dockerfile
  Makefile
  OWNERS
  go.mod
  vendor/modules.txt
Labels: lgtm, approved

#8 NETOBSERV-68: generate ConfigMap for CNO
  Dockerfile
  PROJECT
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/constants/constants.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/ovs/flowsconfig.go
  controllers/ovs/flowsconfig_types.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/helper/helpers.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/github.com/stretchr/objx/.codeclimate.yml
  vendor/github.com/stretchr/objx/.gitignore
  vendor/github.com/stretchr/objx/.travis.yml
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/go.mod
  vendor/github.com/stretchr/objx/go.sum
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/modules.txt
Labels: lgtm, approved

#9 NETOBSERV-63 HPA
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  controllers/constants/constants.go
  controllers/flowcollector_controller.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
Labels: approved

#13 Netobserv 51 console plugin
  README.md
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  go.mod
  go.sum
  main.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/console/v1alpha1/0000_10_consoleplugin.crd.yaml
  vendor/github.com/openshift/api/console/v1alpha1/doc.go
  vendor/github.com/openshift/api/console/v1alpha1/register.go
  vendor/github.com/openshift/api/console/v1alpha1/types.go
  vendor/github.com/openshift/api/console/v1alpha1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved

#20 Configure such as the default case works out of the box
  Makefile
  README.md
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manager/kustomization.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
Labels: lgtm, approved

#21 NETOBSERV-40 Create grafana dashboard
  config/samples/dashboards/Network Observability.json
Labels: lgtm, qe-approved, approved

#22 [NETOBSERV-66] Bug fixes: deploying as a DaemonSet and removing configmap
  controllers/flowcollector_controller_test.go
  controllers/ovs/flowsconfig.go
Labels: bug, lgtm, approved, no-qe

#25 Use ubi8 images
  Dockerfile
Labels: lgtm, approved, no-qe

#27 NETOBSERV-80: Increased testing of goflowkube reconciler (& bugfix)
  controllers/flowcollector_controller_test.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  pkg/helper/testhelpers.go
Labels: lgtm, approved, no-qe

#26 NETOBSERV-91 crd generate
  Makefile
  README.md
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe

#30 Update console plugin arguments
  README.md
  controllers/consoleplugin/consoleplugin_objects.go
Labels: lgtm, approved, no-qe

#23 readme: add mention to loki
  README.md
Labels: lgtm, approved, no-qe

#29 NETOBSERV-90: enable deployment as Daemonset
  config/rbac/role.yaml
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/goflowkube/goflowkube_objects.go
Labels: lgtm, approved, no-qe

#28 NETOBSERV-83 : Namespace configuration
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/constants/constants.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowcollector_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
  controllers/ovs/flowsconfig.go
  controllers/suite_test.go
Labels: lgtm, approved

#31 NETOBSERV-93 Add golangci-lint
  .golangci.yml
  Makefile
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
  controllers/ovs/flowsconfig_types.go
  docs/FlowCollector.md
Labels: lgtm, approved

#33 Adding namespace field to example config file
  config/samples/flows_v1alpha1_flowcollector.yaml
Labels: lgtm, approved, no-qe

#32 NETOBSERV-88: restart pods on configmap change (bugfix)
  controllers/flowcollector_controller_test.go
  controllers/goflowkube/goflowkube_objects.go
  controllers/goflowkube/goflowkube_reconciler.go
  controllers/goflowkube/goflowkube_test.go
Labels: lgtm, approved, no-qe
