Repository netobserv/network-observability-operator, pull requests merged in 2022-04, with the labels that each got.

#72 Make port-forward optional in deploy-loki / grafana
  Makefile
Labels: lgtm, approved

#71 NETOBSERV-126: Allow optional mapping for ports to service names
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller_test.go
  docs/FlowCollector.md
Labels: lgtm, approved

#77 NETOBSERV-218 upgrade base image
  Dockerfile
Labels: lgtm, approved

#79 pointing to the new netobserv-ebpf-agent image and name
  RELEASE.md
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  controllers/constants/constants.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_ebpf_test.go
  docs/FlowCollector.md
Labels: lgtm, approved

#81 NETOBSERV-201: Allow configuring Netobserv agent
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  docs/FlowCollector.md
Labels: lgtm, approved

#82 Modified ebpf "verbose" section by "loglevel"
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  docs/FlowCollector.md
Labels: lgtm

#85 NETOBSERV-304: fix update reconciliation of eBPF agent
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
Labels: lgtm, approved

#86 Allow passing custom env vars to eBPF agent
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  docs/FlowCollector.md
Labels: lgtm, approved

#84 Adding support for FLP operational metrics
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_ebpf.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/flowlogspipeline/flp_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
Labels: lgtm, approved

#88 Update base image to recommended (fixed vulns)
  Dockerfile
Labels: lgtm, approved, ok-to-test

#90 Update release info, include eBPF
  Makefile
  RELEASE.md
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#80 NETOBSERV-297 (v0.1.1) Some Grafana dashboards are not showing up
  config/samples/dashboards/Network Observability.json
Labels: lgtm, approved
