Repository netobserv/network-observability-operator, pull requests merged in 2022-07, with the labels that each got.

#130 Update release doc
  RELEASE.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#131 Doc: remove ambiguity
  README.md
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#122 NETOBSERV-297: Some Grafana dashboards are not showing up
  config/samples/dashboards/Network Observability.json
Labels: lgtm, approved

#115 Document FLP DaemonSet / Deployment kinds subtelties
  Makefile
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: approved

#133 Give a name to console plugin service port
  controllers/consoleplugin/consoleplugin_objects.go
Labels: lgtm, approved

#134 Hack script to "refresh" OVS
  .mk/ocp.mk
  hack/refresh-ovs.sh
Labels: lgtm, approved

#120 NETOBSERV-309 skip TLS checks & add TenantID
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowlogspipeline/flp_objects.go
  docs/FlowCollector.md
  go.mod
  go.sum
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/modules.txt
Labels: lgtm, approved

#137 Fix issues with doc/code/manifest generation
  Makefile
Labels: lgtm, approved

#136 NETOBSERV-397 Kafka TLS
  .mk/development.mk
  DEVELOPMENT.md
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_objects.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/certificates.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/conn_track.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_kafka.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/ingest_kafka.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/tls.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/write_stdout.go
  vendor/modules.txt
Labels: lgtm, approved

#139 Try fixing flaky tests
  controllers/flowcollector_controller_test.go
Labels: lgtm, approved

#126 NETOBSERV-472 Add inital metric to operator
  .mk/development.mk
  .mk/local.mk
  .mk/ocp.mk
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/kubernetes/deployment-prometheus.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/metrics_definitions/bandwidth_per_network_service_per_namespace.yaml
  controllers/flowlogspipeline/metrics_definitions/bandwidth_per_src_subnet.yaml
  controllers/flowlogspipeline/metrics_definitions/network_services_count.yaml
  controllers/flowlogspipeline/test_metrics_definitions/bandwidth_per_network_service_per_namespace.yaml
  controllers/flowlogspipeline/test_metrics_definitions/bandwidth_per_src_subnet.yaml
  controllers/flowlogspipeline/test_metrics_definitions/network_services_count.yaml
  docs/FlowCollector.md
  docs/Metrics.md
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/confgen.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/dedup.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/doc.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/encode.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/extract.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/flowlogs2metrics_config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/grafana_jsonnet.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/transform.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/visualization.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregate.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregates.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/convert.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/exit.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/params_parse.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/timed_cache.go
  vendor/modules.txt
Labels: lgtm, ok-to-test

#138 NETOBSERV-488 Manage FlowCollector readiness / conditions
  Makefile
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/reconcilers/client_helper.go
  docs/FlowCollector.md
  pkg/conditions/conditions.go
Labels: approved
