Repository netobserv/network-observability-operator, pull requests merged in 2022-06, with the labels that each got.

#116 Kafka documentation improvement
  README.md
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#118 NETOBSERV-334 ebpf: flows are logged properly in FLP
  controllers/flowlogspipeline/flp_objects.go
  controllers/flowlogspipeline/flp_test.go
Labels: lgtm

#111 add example workload (with syn attack)
  .mk/development.mk
  .mk/local.mk
  .mk/ocp.mk
  .mk/sample.mk
Labels: lgtm, approved

#121 NETOBSERV-258: configure eBPF agent for Kafka
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/suite_test.go
Labels: approved

#127 README: update intro + loki
  README.md
Labels: lgtm, approved
