Repository netobserv/network-observability-operator, pull requests merged in 2022-12, with the labels that each got.

#206 NETOBSERV-693: use ISO8601 for logging timestamps
  go.mod
  main.go
  vendor/modules.txt
Labels: lgtm, approved

#200 NETOBSERV-719 Documentation update
  .github/workflows/push_image.yml
  Makefile
  README.md
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manifests/bases/description-ocp.md
  config/manifests/bases/description-upstream.md
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  docs/FlowCollector.md
  docs/QuickFilters.md
  docs/assets/network-traffic-main.png
  docs/assets/overview-dashboard.png
  docs/assets/quick-filters.png
  docs/assets/topology-deployment.png
  docs/assets/topology-main.png
  docs/assets/topology-pod.png
Labels: approved

#205 NETOBSERV-727 Update bundle process
  .github/workflows/pull_request.yml
  Makefile
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  config/manifests/bases/description-ocp.md
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Labels: approved

#209 [4.12] Prepare for GA
  Makefile
  bundle.Dockerfile
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/description-ocp.md
  config/manifests/bases/description-upstream.md
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm

#210 Fix operator deploy to use main images by default
  Makefile
Labels: approved

#214 Prevent accidental push
  Makefile
  RELEASE.md
Labels: lgtm

#212 Minor: update operato-sdk version
  Makefile
Labels: lgtm, approved

#208 NETOBSERV-672: Document bug when flowcollector is deployed before kafka
  README.md
Labels: lgtm, approved

#220 NETOBSERV-429: Moved faq&troubleshooting to its own document
  FAQ.md
  README.md
Labels: lgtm, approved

#222 NETOBSERV-412: document architecture
  DEVELOPMENT.md
  docs/Architecture.md
  docs/assets/architecture-direct.png
  docs/assets/architecture-kafka.png
  docs/assets/frontend.png
Labels: lgtm, approved

#218 Bug NETOBSERV-743: update build image & CI tests to Go 1.18 (backport to 4.12)
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
Labels: lgtm, approved

#217 NETOBSERV-743: update build image & CI tests to Go 1.18
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
Labels: lgtm, approved

#223 NETOBSERV-655: move env to debug section (4.12 backport)
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
Labels: lgtm, approved, breaking-change

#227 Update golangci-lint
  .golangci.yml
  Makefile
Labels: lgtm

#228 Update golangci-lint (release-4.12)
  .golangci.yml
  Makefile
Labels: lgtm

#225 [4.12 backport] CRD doc update - simplified sample (#224)
  Makefile
  api/v1alpha1/flowcollector_types.go
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#229 NETOBSERV-730 Change operator limits
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#226 NETOBSERV-750: fix to enable being in the 4.12 catalog
  Makefile
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/suite_test.go
  docs/FlowCollector.md
  main.go
Labels: lgtm, approved, ok-to-test, breaking-change

#232 NETOBSERV-750: fix to enable being in the 4.12 catalog (release-4.12 backport)
  Makefile
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/suite_test.go
  docs/FlowCollector.md
  main.go
Labels: lgtm, approved

#231 [4.12 backport] NETOBSERV-730 Change operator limits (#229)
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#234 NETOBSERV-704 Netflow traffic page doesn't appear sometimes
  FAQ.md
Labels: lgtm, approved, no-qe

#237 Remove mention 'cannot be updated' on requests/limits
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#238 [4.12][doc] Remove mention of 'cannot be updated' on requests/limits
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#236 NETOBSERV-760 Add ascidoc doc
  .gitignore
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1alpha1.adoc
  hack/asciidoc-gen-config.yaml
  hack/asciidoc-gen.sh
Labels: lgtm, approved

#188 NETOBSERV-565 added service monitors for flp prometheus and console plugin
  .mk/local.mk
  .mk/ocp.mk
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/flowcollector_controller.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  go.mod
  go.sum
  main.go
  pkg/discover/apis.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm
