Repository netobserv/network-observability-operator, pull requests merged in 2022-09, with the labels that each got.

#151 Improve release doc & script
  Makefile
  RELEASE.md
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  controllers/flowcollector_controller_console_test.go
Labels: lgtm, approved

#160 NETOBSERV-467 Updated defaults (eBPF / sampling), update doc
  README.md
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#162 NETOBSERV-448: Moving agent type, ipfix and ebpf config into their own common subsection.
  Makefile
  README.md
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors_envtpl.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  docs/FlowCollector.md
  hack/refresh-ovs.sh
Labels: lgtm, approved, breaking-change

#158 NETOBSERV-396: Flp prom tls
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_objects.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/certificates.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_filter.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/confgen.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/encode.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/extract.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/transform.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/visualization.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregate.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#157 Workflows update
  .github/workflows/push_image.yml
  Makefile
Labels: lgtm, approved

#155 NETOBSERV-435 - Set default req/limits resources for eBPF agent
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#161 Add default limits to CR
  config/samples/flows_v1alpha1_flowcollector.yaml
Labels: lgtm, approved

#163 NETOBSERV-448: reviewing API to follow conventions
  Makefile
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors_envtpl.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  docs/FlowCollector.md
Labels: documentation, lgtm, approved, breaking-change

#164 NETOBSERV-433 and NETOBSERV-373 - unify names
  .mk/local.mk
  .mk/ocp.mk
  DEVELOPMENT.md
  Makefile
  README.md
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-manager-config_v1_configmap.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/constants/constants.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  docs/FlowCollector.md
  hack/deploy-grafana.sh
  main.go
Labels: lgtm, approved

#166 Fix scc for sample-workload
  .mk/sample.mk
Labels: lgtm, approved

#167 Allow enabling profiler port in FLP
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_objects.go
  docs/FlowCollector.md
Labels: lgtm, approved

#168 Fix eBPF agent's sampling: 0 value to disabled
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
Labels: bug, lgtm, approved, ok-to-test

#171 NETOBSERV-589: setup FLP transformer to receive protobuf for eBPF mode
  controllers/flowlogspipeline/flp_objects.go
Labels: lgtm, approved, ok-to-test

#173 NETOBSERV-579 Use netobserv prefix, add 4 new metrics, remove one
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/metrics_definitions/bandwidth_per_network_service_per_namespace.yaml
  controllers/flowlogspipeline/metrics_definitions/node_received_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_sent_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/received_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/sent_bytes_total.yaml
  docs/FlowCollector.md
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/api.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/conntrack.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/enum.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/extract_aggregate.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/extract_timebased.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/ingest_kafka.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/confgen.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/doc.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/extract.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/flowlogs2metrics_config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/stage_params.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregate.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/multiorderedmap.go
  vendor/modules.txt
Labels: lgtm, approved

#170 Expose new Kafka parameters + tweak defaults
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  docs/FlowCollector.md
Labels: lgtm, approved
