Repository netobserv/network-observability-operator, pull requests merged in 2022-10, with the labels that each got.

#174 Kafka mk targets
  .mk/development.mk
Labels: lgtm, approved

#176 Remove unused pipeline transfo and metrics
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/metrics_definitions/bandwidth_per_src_subnet.yaml
  controllers/flowlogspipeline/metrics_definitions/network_service_total.yaml
Labels: lgtm, approved

#175 NETOBSERV-489: Use authorize feature from console plugin API
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test

#178 Fix auth token mode for FLP
  controllers/flowlogspipeline/flp_common_objects.go
Labels: lgtm, approved

#180 NETOBSERV-578: allow passing env vars to FLP
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
Labels: lgtm, ok-to-test

#179 NETOBSERV-466: Add metric to count packet number in FLP
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test

#182 NETOBSERV-447: Changed default FLP retry value to prevent FLP beeing oom-killed
  api/v1alpha1/flowcollector_types.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#181 NETOBSERV-660: Create metric section
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test, breaking-change

#183 NETOBSERV-645 Kafka export (flagged as experimental feature)
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  docs/FlowCollector.md
Labels: lgtm, approved

#184 NETOBSERV-382: Added status field in HPA configuration
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  docs/FlowCollector.md
Labels: lgtm, approved
