Repository netobserv/network-observability-operator, pull requests merged in 2022-11, with the labels that each got.

#191 NETOBSERV-694: add missing annotations to netobserv-privileged namespace
  controllers/ebpf/internal/permissions/permissions.go
Labels: lgtm, approved, ok-to-test

#192 NETOBSERV-619: Fix dedupe env name for EBPF
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved

#193 NETOBSERV-638: avoid infinite update-retrigger loop
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  go.mod
  go.sum
  pkg/helper/helpers.go
  pkg/helper/helpers_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
Labels: lgtm

#195 NETOBSERV-708: regenerate bundle CSV, CRD and other manifests
  Makefile
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Labels: lgtm, approved

#196 NETOBSERV-712 Add metric to measure number of flows per namespace
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml
Labels: lgtm, approved, ok-to-test

#190 NETOBSERV-690 (spike): move eBPF image pullspec from CRD to CSV
  DEVELOPMENT.md
  Makefile
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/version_in_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors_envtpl.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/operator/config.go
  controllers/suite_test.go
  docs/FlowCollector.md
  main.go
Labels: lgtm, approved

#197 NETOBSERV-690: move console and FLP image pullspecs from CRD to CSV
  DEVELOPMENT.md
  Makefile
  api/v1alpha1/flowcollector_types.go
  bundle.Dockerfile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/version_in_flowcollectors.yaml
  config/crd/patches/version_in_flowcollectors_envtpl.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/operator/config.go
  controllers/suite_test.go
  docs/FlowCollector.md
  main.go
Labels: lgtm, approved

#198 Amend image patching instructions
  DEVELOPMENT.md
  config/manager/manager.yaml
Labels: lgtm, approved

#201 Add make script to update images
  .mk/development.mk
  DEVELOPMENT.md
Labels: lgtm, approved

#203 fix make run (ocp and local)
  .mk/local.mk
  .mk/ocp.mk
  .mk/sample.mk
Labels: lgtm, approved
