Repository netobserv/network-observability-operator, pull requests merged in 2023-08, with the labels that each got.

#400 NETOBSERV-1222: Pull request template
  .github/pull_request_template.md
Labels: lgtm, approved, jira/valid-reference

#386 NETOBSERV-1182 added cluster name to flp configuration
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/globals/globals.go
  docs/FlowCollector.md
Labels: lgtm, qe-approved, approved, ok-to-test

#404 NETOBSERV-1232 "netobserv" NS is not excluded from Applications for Flow dashboards
  controllers/flowcollector_controller.go
  controllers/flowcollector_objects.go
  controllers/infra_health_dashboard.json
  pkg/helper/dashboard.go
Labels: lgtm, approved, ok-to-test

#407 NETOBSERV-1104: remove italic text in CRD doc
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#403 NETOBSERV-1224 Flowcollector does not report status != Ready in OCP Console
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  pkg/conditions/conditions.go
Labels: lgtm, qe-approved, approved
