Repository netobserv/network-observability-operator, pull requests merged in 2023-12, with the labels that each got.

#486 NETOBSERV-1398: fix loki url when same namespace
  api/v1alpha1/flowcollector_webhook.go
  api/v1beta1/flowcollector_webhook.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  controllers/flowlogspipeline/flp_test.go
  pkg/helper/loki_config.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#503 NETOBSERV-1358: splitting controllers
  api/v1alpha1/flowcollector_types.go
  api/v1beta1/flowcollector_types.go
  api/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/controllers.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_ingest_objects.go
  controllers/flp/flp_ingest_reconciler.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_objects.go
  controllers/flp/flp_transfo_reconciler.go
  controllers/globals/globals.go
  controllers/monitoring/monitoring_controller.go
  controllers/monitoring/monitoring_objects.go
  controllers/reconcilers/common.go
  controllers/reconcilers/namespaced_objects_manager.go
  controllers/reconcilers/reconcilers.go
  controllers/suite_test.go
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  main.go
  pkg/conditions/conditions.go
  pkg/helper/client_helper.go
  pkg/helper/flowcollector.go
  pkg/manager/config.go
  pkg/manager/manager.go
  pkg/manager/status/namespace.go
  pkg/manager/status/status_manager.go
  pkg/manager/status/status_manager_test.go
  pkg/manager/status/statuses.go
  pkg/narrowcache/client.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#509 NETOBSERV-1406 Remove RTT unsupported mentions
  api/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
Labels: lgtm, approved, no-qe

#514 NETOBSERV-1432 Missing drops information in table view
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#515 NETOBSERV-1434: update health dashboard for changed operator metric
  Makefile
  pkg/dashboards/infra_health_dashboard.json
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#511 NETOBSERV: 1374 Make enums pascal case
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/flowcollector_webhook.go
  api/v1beta1/flowcollector_webhook_test.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/flowcollector_types.go
  api/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flp/flp_common_objects.go
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  pkg/conversion/conversion.go
  pkg/conversion/conversion_test.go
Labels: lgtm, qe-approved, approved, testing-breaking-change

#513 NETOBSERV-1422: fix missing "buckets" in generated promql
  controllers/monitoring/monitoring_controller_test.go
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboard_test.go
  pkg/dashboards/model.go
  pkg/test/dashboards.go
Labels: lgtm, approved, jira/valid-reference
