Repository netobserv/network-observability-operator, pull requests merged in 2023-07, with the labels that each got.

#387 NETOBSERV-1131: Filter for Duplicate=false in metrics
  controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/stage_params.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#390 github ok-to-test: add more info in comment
  .github/workflows/push_image_pr.yml
  dummy
Labels: lgtm, approved

#393 Upgrade linter - fix found issues - use go1.20
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Makefile
  api/v1alpha1/flowcollector_webhook.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_objects.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  go.mod
  pkg/watchers/watcher_test.go
Labels: lgtm, approved

#382 NETOBSERV-1107: Add GoMemLimit env setting to prevent ebpf agent OOM conditions
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, jira/valid-reference

#395 NETOBSERV-1190: change DNS to use latency instead of TS
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved, jira/valid-reference

#396 NETOBSERV-1197: Generalize TCPDrop to include other prototocl drops
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference
