Repository netobserv/network-observability-operator, pull requests merged in 2023-02, with the labels that each got.

#254 NETOBSERV-793 Change default loki CA configmap name
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#261 NETOBSERV-793 [1.2 backport] Change default loki CA configmap name (#254)
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
Labels: lgtm, approved

#250 NETOBSERV-674 : Added management of prometheus rule
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/flowcollector_controller.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  pkg/helper/comparators.go
Labels: lgtm, approved

#265 NETOBSERV-674: Added alertNamespaces field in console plugin frontend configuration
  controllers/consoleplugin/consoleplugin_objects.go
Labels: lgtm, approved, jira/valid-reference

#269 NETOBSERV-896: update operator capability
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#262 NETOBSERV-856 Fix infinite reconcile & add more debugging utility
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  pkg/helper/change_report.go
  pkg/helper/comparators.go
Labels: lgtm, approved, ok-to-test

#274 Fix netobserv operator bundle deploy
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Makefile
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/kustomization.yaml
  config/manifests/kustomization.yaml
  config/openshift-olm/kustomization.yaml
  config/openshift-olm/namespace.yaml
  config/openshift-olm/patch.yaml
  config/webhook/manifests.yaml
Labels: lgtm, approved, ok-to-test

#272 Fix doc for operator-sdk command & make generate now must be explicit
  DEVELOPMENT.md
  Makefile
  RELEASE.md
Labels: lgtm, approved, no-qe, no-doc

#264 NETOBSERV-155: Added sampling field to console frontend configuration
  api/v1alpha1/flowcollector_types.go
  api/v1beta1/flowcollector_types.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  pkg/helper/flowcollector.go
Labels: lgtm, approved, jira/valid-reference

#277 Fix deployment on non-ovnk (e.g. kind)
  controllers/ovs/flowsconfig_ovnk_reconciler.go
Labels: lgtm, approved, no-qe, no-doc

#276 Upstream release note improvements
  .mk/development.mk
  Makefile
  RELEASE.md
Labels: lgtm, approved, no-qe, no-doc
