Repository netobserv/network-observability-operator, pull requests merged in 2023-09, with the labels that each got.

#394 NETOBSERV-1110: Enable support for Flow RTT
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: enhancement, lgtm, approved, no-qe, ok-to-test, breaking-change, jira/valid-reference, no-doc

#410 fix DNStracking and packet drop features name in the API
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved

#406 NETOBSERV-1283: Enable netns mount for privileged pods
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#379 NETOBSERV-1087: Added fields for ca certificate configuration
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  docs/FlowCollector.md
  pkg/helper/monitoring.go
  pkg/helper/monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#411 Remove ConfigOrSecret API, replaced with the newer FileReference
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_reconciler.go
  docs/FlowCollector.md
  pkg/volumes/builder.go
  pkg/watchers/object_ref.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
Labels: lgtm, approved, no-qe, breaking-change, no-doc

#412 Regenerate API reference asciidoc
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta1.adoc
  hack/asciidoc-gen.sh
Labels: lgtm, approved

#414 NETOBSERV-1295: Fix cacert monitoring copy
  controllers/constants/constants.go
  controllers/flowcollector_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  pkg/watchers/watcher.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#416 NETOBSERV-1295 backport: Fix certs monitoring copy
  controllers/constants/constants.go
  controllers/flowcollector_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  pkg/watchers/watcher.go
Labels: lgtm, approved

#417 Consolidate flow json spec
  docs/flows-format.adoc
  hack/asciidoc-flows-gen.sh
  hack/flows-format-header.adoc
Labels: approved

#429 NETOBSERV-1314: cleanup old objects after upgrade [1.4 backport]
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/helper/flowcollector.go
  pkg/test/kube_mock.go
  pkg/watchers/watcher_test.go
Labels: jira/valid-reference

#427 NETOBSERV-1314: cleanup old objects after upgrade
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/helper/flowcollector.go
  pkg/test/kube_mock.go
  pkg/watchers/watcher_test.go
Labels: lgtm, approved, jira/valid-reference, no-doc

#428 Update dev doc
  DEVELOPMENT.md
Labels: lgtm, approved, no-qe, no-doc

#409 NETOBSERV-314: NETOBSERV-1274 index type and duplicate (improve query perfs)
  controllers/constants/constants.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
Labels: approved, no-qe, jira/valid-reference, no-doc

#426 Remove unsupported mention on IPFIX doc
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta1.adoc
  hack/asciidoc-gen.sh
Labels: lgtm, qe-approved, approved
