Repository netobserv/network-observability-operator, pull requests merged in 2023-10, with the labels that each got.

#446 Added console method of image swapping to docs
  DEVELOPMENT.md
  docs/assets/console-csv.png
Labels: lgtm, approved

#440 NETOBSERV-1340: Add operator to "Observability" category in OperatorHub
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-reference

#444 NETOBSERV-1346: Added checks to prevent dereferencing Provided cert nil pointer
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  pkg/volumes/builder.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#450 NETOBSERV-1293: Fix status oscillation
  pkg/helper/client_helper.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#449 NETOBSERV-754: add pprof, improve memory footprint
  .mk/development.mk
  DEVELOPMENT.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/flowcollector_controller.go
  main.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference, no-doc

#455 Updated zero-click Loki references from 1G to 10G
  README.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
Labels: lgtm, approved

#430 Small doc updates - feedback from osdocs
  api/v1beta1/flowcollector_types.go
  api/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#458 NETOBSERV-1354: fix concurrent access on watches
  pkg/watchers/watcher.go
Labels: lgtm, approved, no-qe, ok-to-test, jira/valid-reference, no-doc

#461 Workflow: build images from release branches
  .github/workflows/push_image.yml
Labels: lgtm, approved

#456 NETOBSERV-1344: include inner traffic in metrics [1.4 backport]
  controllers/flowlogspipeline/metrics_definitions/namespace_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/namespace_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/namespace_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/namespace_ingress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#463 Workflow: set release related img when relevant
  .github/workflows/push_image_pr.yml
Labels: lgtm, approved

#454 NETOBSERV-764 followup monolith & distributed modes
  Makefile
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_webhook.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/flowcollector_types.go
  api/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  config/samples/flows_v1beta2_flowcollector_lokistack.yaml
  controllers/flowcollector_controller_test.go
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  pkg/helper/flowcollector.go
Labels: lgtm, approved

#473 NETOBSERV-1371: Disable http/2 in kube-rbac-proxy [1.4 backport]
  .github/workflows/pull_request.yml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  go.mod
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#475 Add v1alpha1 back to registered schemes + fix YQ issues
  Makefile
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  main.go
Labels: lgtm, approved, no-qe, no-doc

#464 NETOBSERV-1245: NETOBSERV-1304: to enable DNS we no longer require privileged
  controllers/ebpf/agent_controller.go
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#466 NETOBSERV-1369: Disable http/2
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/constants/constants.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  main.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference, no-doc
