Repository netobserv/network-observability-operator, pull requests merged in 2023-04, with the labels that each got.

#315 NETOBSERV-963, revert most of cert watching [1.2 backport]
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/reconcilers/client_helper.go
  pkg/helper/certificates.go
Labels: lgtm, approved

#312 NETOBSERV-963 revert most of cert watching
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/reconcilers/client_helper.go
  pkg/helper/certificates.go
Labels: lgtm, qe-approved, approved, ok-to-test

#320 NETOBSERV-844 skip empty cert paths
  controllers/consoleplugin/consoleplugin_objects.go
Labels: lgtm, approved

#321 [Backport] NETOBSERV-844 skip empty cert paths
  controllers/consoleplugin/consoleplugin_objects.go
Labels: lgtm, qe-approved, approved

#300 Add workflow test hack
  .github/workflows/push_image.yml
  Makefile
  hack/test-workflow.sh
Labels: lgtm, approved

#327 NETOBSERV-993 Restore default metrics
  api/v1alpha1/flowcollector_types.go
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  docs/FlowCollector.md
Labels: lgtm, qe-approved, approved, ok-to-test

#328 NETOBSERV-976 Fix disabling alerts
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_test.go
  pkg/helper/comparators.go
Labels: lgtm, qe-approved, approved, ok-to-test
