Repository netobserv/network-observability-operator, pull requests merged in 2023-03, with the labels that each got.

#280 Fix regression on deploying latest
  DEVELOPMENT.md
  Makefile
Labels: lgtm, qe-approved, approved

#287 NETOBSERV-897 Report coverage
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#284 KIND: Fix output path for api conversation generation + Fix webhook ca bundle injection for flow-collector CRD
  Makefile
  config/kubernetes/cainjection_in_flowcollectors.yaml
  config/kubernetes/kustomization.yaml
Labels: lgtm, approved, no-qe, no-doc

#282 NETOBSERV-736: Added downstream deployment configuration for monitoring collection
  .mk/development.mk
  DEVELOPMENT.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/flowcollector_controller.go
  controllers/flowcollector_objects.go
  controllers/operator/config.go
  controllers/reconcilers/client_helper.go
  controllers/suite_test.go
  main.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#260 Grafana dashboards
  .mk/ocp.mk
  controllers/flowcollector_controller.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
  pkg/discover/apis.go
Labels: lgtm, approved

#293 Push temporary bundle/catalog
  .github/workflows/push_image_pr.yml
  Makefile
Labels: lgtm, approved

#291 Fix remaining Makefile issues + annoying bundle date
  .github/workflows/pull_request.yml
  DEVELOPMENT.md
  Makefile
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#273 Enable operator metrics collection
  bundle/manifests/netobserv-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/netobserv-metrics-service_v1_service.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/openshift-olm/kustomization.yaml
  config/openshift-olm/monitor.yaml
  config/openshift-olm/monitoring-patch.yaml
  config/openshift/kustomization.yaml
  config/openshift/monitor.yaml
  config/openshift/monitoring-patch.yaml
  config/prometheus/kustomization.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/flowcollector_controller.go
  controllers/flowcollector_objects.go
Labels: lgtm, qe-approved, approved

#290 NETOBSERV-909 fix servicemonitor & prom rule reconcile
  .github/workflows/pull_request.yml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/reconcilers/namespaced_objects_manager.go
  controllers/suite_test.go
  pkg/discover/apis.go
  pkg/helper/comparators.go
  test-assets/prometheusrule.yaml
  test-assets/servicemonitors.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#298 Run codecov only for go1.19
  .github/workflows/pull_request.yml
Labels: approved

#294 NETOBSERV-918 dashboards follow-up
  api/v1alpha1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/suite_test.go
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1alpha1.adoc
Labels: lgtm, approved

#303 NETOBSERV-928 Connection tracking renaming
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  config/samples/flows_v1beta1_flowcollector_versioned.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/constants/constants.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test, breaking-change

#299 NETOBSERV-123: Added infra health dashboard
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_test.go
  controllers/flowcollector_objects.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/infra_health_dashboard.json
  controllers/reconcilers/client_helper.go
Labels: lgtm, approved, jira/valid-reference

#302 NETOBSERV-927 Improve servicemonitor/prometheusrule checking changes …
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  pkg/helper/comparators.go
Labels: lgtm, approved, no-qe, no-doc

#305 Enable TCP flags handling in FLP
  controllers/flowlogspipeline/flp_common_objects.go
Labels: lgtm, approved, ok-to-test

#306 NETOBSERV-918 Update v1beta1 with modified defaults
  Makefile
  README.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manifests/bases/description-ocp.md
  config/manifests/bases/description-upstream.md
  config/samples/flows_v1alpha1_flowcollector_versioned.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  config/samples/flows_v1beta1_flowcollector_versioned.yaml
  config/samples/kustomization.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#307 NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved

#309 [Backport] NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved

#308 NETOBSERV-904: Make v1beta1 the storage version
  api/v1alpha1/flowcollector_types.go
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flowcollector_controller_console_test.go
Labels: lgtm, approved, no-qe, ok-to-test, jira/valid-reference, no-doc

#314 Change metrics rates calculations from 5m to 1m
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/infra_health_dashboard.json
Labels: lgtm, approved
