Repository netobserv/network-observability-operator, pull requests merged in 2023-06, with the labels that each got.

#356 NETOBSERV-1005 dashboard: use sum...by
  .mk/development.mk
  controllers/flowlogspipeline/metrics_definitions/namespace_flows_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/node_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_egress_packets_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_bytes_total.yaml
  controllers/flowlogspipeline/metrics_definitions/workload_ingress_packets_total.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#360 NETOBSERV-1076 Fix service change detection
  pkg/helper/comparators.go
Labels: lgtm, qe-approved, approved, ok-to-test

#361 NETOBSERV-1076 Fix service change detection [1.3 backport]
  pkg/helper/comparators.go
Labels: lgtm, qe-approved, approved

#364 CRD doc updates
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta1.adoc
  hack/asciidoc-gen.sh
Labels: lgtm, qe-approved, approved

#367 [Backport] NETOBSERV-1050 & NETOBSERV-1065 Transport field in IPFIX exporter not working
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
Labels: lgtm, qe-approved, approved

#366 Backporting doc updates to 1.3
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta1.adoc
  hack/asciidoc-gen.sh
Labels: lgtm, approved

#365 NETOBSERV-1070: Fix reconcile from DISABLED to AUTO configuration
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/reconcilers/common.go
Labels: lgtm, approved, jira/valid-reference

#368 NETOBSERV-1070: Fix reconcile from DISABLED to AUTO configuration [Backport 1.3]
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  controllers/reconcilers/common.go
Labels: lgtm, approved, jira/valid-reference

#313 NETOBSERV-915 add conversation direction
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/conntrack.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, ok-to-test

#369 [Backport] NETOBSERV-915 add conversation direction
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/conntrack.go
  vendor/modules.txt
Labels: lgtm, approved

#373 Fix outdated upstream doc on user access
  README.md
Labels: approved

#375 NETOBSERV-1076 Fix CR stuck in Updating state [1.3 backport]
  Makefile
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_test.go
  controllers/reconcilers/namespaced_objects_manager.go
  pkg/helper/client_helper.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
Labels: lgtm, qe-approved, approved, ok-to-test

#381 Add IBM Z (s390x)
  .github/workflows/push_image.yml
  .github/workflows/release.yml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  hack/test-workflow.sh
Labels: lgtm, approved, no-qe, no-doc

#377 NETOBSERV-974: Add SASL support for KAFKA (unsupported feature)
  Makefile
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  controllers/ebpf/agent_controller_test.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/flowcollector.go
  pkg/volumes/builder.go
  pkg/watchers/object_ref.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/api.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_kafka.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/enum.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/extract_aggregate.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/ingest_kafka.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/sasl.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/tls.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/confgen.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/dedup.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/doc.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/extract.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/confgen/flowlogs2metrics_config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/stage_params.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregate.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregates.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/batcher.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/connections.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/exit.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/multiorderedmap.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/params_parse.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/prom_server.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/timed_cache.go
  vendor/modules.txt
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#370 Doc updates:
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta1.adoc
  hack/asciidoc-gen.sh
Labels: approved

#383 (trivial) makefile: avoid kubectl calls in global scope
  .mk/development.mk
Labels: lgtm, approved, no-qe, no-doc

#354 NETOBSERV-1053 optionnal loki / console plugin
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test

#385 Add nil-check for loki.enable
  controllers/flowlogspipeline/flp_common_objects.go
  pkg/helper/flowcollector.go
Labels: lgtm, approved
