Repository netobserv/network-observability-operator, pull requests merged in 2023-05, with the labels that each got.

#310 NETOBSERV-765 Add CA/Secret config to ServiceMonitor
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/reconcilers/namespaced_objects_manager.go
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test

#311 NETOBSERV-986 - IPFIX exporter implementation
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/flowcollector_webhook.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/api.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/ingest_synthetic.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/stage_params.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/extract/aggregate/aggregates.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/connections.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/pipeline/utils/timed_cache.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/convert.go
  vendor/modules.txt
Labels: lgtm, approved

#334 Improve script to replace images for OLM
  .mk/development.mk
  DEVELOPMENT.md
  hack/swap-image-csv.sh
Labels: lgtm, approved, no-qe, no-doc

#332 Update list of maintainers
  OWNERS
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manifests/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, approved, no-qe, no-doc

#333 NETOBSERV-1003: Added monitoring role to bundle
  config/openshift-olm/monitor.yaml
  config/openshift/monitor.yaml
Labels: lgtm, qe-approved, approved, jira/valid-reference

#336 fix makefile
  .github/workflows/push_image_pr.yml
  Makefile
Labels: lgtm, approved

#338 fix typo in GH actions
  .github/workflows/push_image_pr.yml
Labels: lgtm, approved

#342 Attempt to fix multiarch workflow
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .mk/shortcuts.mk
  DEVELOPMENT.md
  Makefile
  hack/test-workflow.sh
Labels: lgtm, approved

#345 Prefer docker over podman in CI
  Makefile
  hack/test-workflow.sh
Labels: lgtm

#348 Dummy PR test bundle/catalog GH push flow
  .github/workflows/push_image_pr.yml
Labels: ok-to-test

#353 Fix bundle and PR tests
  .github/workflows/pull_request.yml
  bundle/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/netobserv-openshift-netobserv-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: lgtm, approved

#346 Update bundle and catalog push GH actions
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Makefile
  shortlived.Dockerfile
Labels: lgtm, approved

#326 NETOBSERV-773 Copy certificates across namespaces
  api/v1alpha1/flowcollector_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1beta1/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/constants/constants.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flowlogspipeline/flp_common_objects.go
  controllers/flowlogspipeline/flp_ingest_objects.go
  controllers/flowlogspipeline/flp_ingest_reconciler.go
  controllers/flowlogspipeline/flp_monolith_objects.go
  controllers/flowlogspipeline/flp_monolith_reconciler.go
  controllers/flowlogspipeline/flp_reconciler.go
  controllers/flowlogspipeline/flp_test.go
  controllers/flowlogspipeline/flp_transfo_objects.go
  controllers/flowlogspipeline/flp_transfo_reconciler.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  controllers/reconcilers/common.go
  controllers/reconcilers/namespaced_objects_manager.go
  controllers/suite_test.go
  docs/FlowCollector.md
  pkg/helper/certificates.go
  pkg/helper/client_helper.go
  pkg/helper/flowcollector.go
  pkg/helper/tokens.go
  pkg/test/kube_mock.go
  pkg/volumes/builder.go
  pkg/watchers/certificates_watcher.go
  pkg/watchers/certificates_watcher_test.go
  pkg/watchers/object_ref.go
  pkg/watchers/watchables.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
Labels: qe-approved, approved, ok-to-test
