Repository netobserv/network-observability-operator, pull requests merged in 2024-03, with the labels that each got.

#584 NETOBSERV-1544: fix broken link and update a few other links in CSV
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
Labels: lgtm, jira/valid-reference

#562 NETOBSERV-1500: Update after refactoring of FLP transform network API
  controllers/flp/flp_pipeline_builder.go
  go.mod
  go.sum
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: lgtm, approved, do-not-merge/hold, no-qe, jira/valid-reference, no-doc

#579 NETOBSERV-1517: remove IPFIX agent mode
  README.md
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/descriptions/upstream.md
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_controller_test.go
  controllers/flp/flp_ingest_objects.go
  controllers/flp/flp_ingest_reconciler.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  controllers/ovs/flowsconfig_types.go
  controllers/suite_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/flowcollector.go
  pkg/loki/labels.go
  pkg/manager/status/status_manager.go
  pkg/metrics/predefined_metrics.go
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#578 NETOBSERV-1466 NodeDirection / IfDirection
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/constants/constants.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  pkg/loki/labels.go
Labels: lgtm, approved, breaking-change

#589 NETOBSERV-1514: drop go1.20 support
  .github/workflows/pull_request.yml
  go.mod
Labels: lgtm, approved, jira/valid-reference

#576 NETOBSERV-1474: change dup mode to use list as the default
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#593 NETOBSERV-1568: reintroduce finalizer check to remove any remaining finalizer
  controllers/flowcollector_controller.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#569 NETOBSERV-1508 add selector, afinity and priority to components
  Makefile
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/flowcollector_webhook_test.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/agent_controller_test.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  pkg/helper/comparators.go
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test

#600 NETOBSERV-1471 eBPF env renaming
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
Labels: lgtm, approved, do-not-merge/hold

#601 Change HOST/PORT env to TARGET_HOST / TARGET_PORT
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_ebpf_test.go
Labels: lgtm, approved, ok-to-test

#603 Add go mod vendor check in CI
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#602 NETOBSERV-1532: add TLS support to ebpf agent metrics config
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/openshift/namespace.yaml
  controllers/ebpf/agent-metrics-test.go
  controllers/ebpf/agent-metrics.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/reconcilers/common.go
  docs/FlowCollector.md
  pkg/helper/monitoring.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference
