Repository netobserv/network-observability-operator, pull requests merged in 2024-05, with the labels that each got.

#609 NETOBSERV-1343: generate dashboards from metrics API
  Makefile
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/samples/flowmetrics/az_aware_worloads_traffic.yaml
  config/samples/flowmetrics/cluster_external_egress_rtt_seconds.yaml
  config/samples/flowmetrics/cluster_external_egress_traffic.yaml
  config/samples/flowmetrics/cluster_external_ingress_rtt_seconds.yaml
  config/samples/flowmetrics/cluster_external_ingress_traffic.yaml
  config/samples/flowmetrics/pods_incoming_bytes.yaml
  config/samples/flowmetrics/pods_openshift_ingress.yaml
  config/samples/flowmetrics/pods_outgoing_bytes.yaml
  config/samples/flowmetrics/service_ports.yaml
  config/samples/flowmetrics/services_incoming_bytes.yaml
  config/samples/flowmetrics/traffic_across_az.yaml
  config/samples/flows_v1alpha1_flowmetric.yaml
  controllers/flp/flp_controller.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  controllers/flp/metrics_api_test.go
  controllers/monitoring/monitoring_controller.go
  controllers/monitoring/monitoring_controller_test.go
  controllers/monitoring/monitoring_objects.go
  controllers/reconcilers/common.go
  controllers/reconcilers/reconcilers.go
  docs/FlowMetric.md
  docs/Metrics.md
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/dashboards/dashboard.go
  pkg/dashboards/dashboard_test.go
  pkg/dashboards/health.go
  pkg/dashboards/model.go
  pkg/dashboards/scopes.go
  pkg/metrics/helper.go
  pkg/metrics/predefined_charts.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#634 NETOBSERV-1613: switch kubectl apply to use server-side
  Makefile
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#629 NETOBSERV-1447: Added a check to log a warning if some labels are used in metric defi…
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  pkg/helper/helpers.go
  pkg/helper/helpers_test.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#639 NETOBSERV-1632: metrics API, allow empty unit
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  docs/FlowMetric.md
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#640 NETOBSERV-1625: (follow-up) mention other possible cause for ebpf drops
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent-metrics.go
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe, jira/valid-reference

#643 Replace "handshake RTT" mentions with "smoothed RTT"
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe

#645 NETOBSERV-140: top pods talkers (and other sample updates)
  config/samples/flowmetrics/az_aware_worloads_traffic.yaml
  config/samples/flowmetrics/cluster_external_egress_rtt_seconds.yaml
  config/samples/flowmetrics/cluster_external_egress_traffic.yaml
  config/samples/flowmetrics/cluster_external_ingress_rtt_seconds.yaml
  config/samples/flowmetrics/cluster_external_ingress_traffic.yaml
  config/samples/flowmetrics/pods_egress_rtt_seconds.yaml
  config/samples/flowmetrics/pods_egress_traffic.yaml
  config/samples/flowmetrics/pods_incoming_bytes.yaml
  config/samples/flowmetrics/pods_ingress_rtt_seconds.yaml
  config/samples/flowmetrics/pods_ingress_traffic.yaml
  config/samples/flowmetrics/pods_openshift_ingress_traffic.yaml
  config/samples/flowmetrics/pods_outgoing_bytes.yaml
  config/samples/flowmetrics/root_ports_flows.yaml
  config/samples/flowmetrics/service_ports.yaml
  config/samples/flowmetrics/services_incoming_bytes.yaml
  config/samples/flowmetrics/services_ports_traffic.yaml
  config/samples/flowmetrics/traffic_across_az.yaml
Labels: lgtm, approved, no-qe, jira/valid-reference

#644 use the same string for flowdrop alert to disable alert if needed
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
Labels: lgtm, approved, no-qe, no-doc

#649 enable ebpf metrics by default while keep the knob in case we need to disable
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved

#650 NETOBSERV-1648: Make high cardinality check more visible
  Makefile
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/config/config.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_controller_flowmetrics_test.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/fmstatus/flowmetrics_status.go
  docs/FlowMetric.md
  pkg/helper/cardinality.go
  pkg/helper/cardinality_test.go
  pkg/helper/helpers.go
  pkg/helper/helpers_test.go
  pkg/manager/manager.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#653 NETOBSERV-1647: do not get Loki certificates when Loki is disabled
  controllers/flp/flp_controller.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_transfo_reconciler.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#613 NETOBSERV-739: Add prometheus
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller_iso_test.go
  docs/FlowCollector.md
  docs/Metrics.md
  pkg/helper/flowcollector.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
Labels: qe-approved, ok-to-test, jira/valid-reference

#659 Bump ubi9.4
  Dockerfile
Labels: no-qe, no-doc

#658 [Trivial] Remove obsolete fix, add --server-side to deploy-kind
  .mk/development.mk
  .mk/local.mk
Labels: lgtm, approved, no-qe, no-doc
