Repository netobserv/network-observability-operator, pull requests merged in 2024-09, with the labels that each got.

#755 fix filter icmp pointer check [BP 1.6,.2]
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, ok-to-test

#754 fix filter icmp pointer check
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved

#664 NETOBSERV-1642: Ovs monitoring feature
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#738 NETOBSERV-1779 allow port filtering if protocol not set
  controllers/ebpf/agent_controller.go
Labels: lgtm, qe-approved, approved, ok-to-test

#739 NETOBSERV-1792: Added update-build script to add downstream labels
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
  hack/patch_csv.py
  hack/update-build.sh
Labels: lgtm, approved, jira/valid-reference

#758 Update catalog file to point to downstream bundle
  hack/patch_catalog.py
  hack/update-build.sh
Labels: lgtm, approved

#759 Add missing dependencies to build scripts
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
Labels: lgtm, approved

#760 Fix image reference
  hack/patch_catalog.py
  hack/patch_csv.py
Labels: lgtm, approved

#741 NETOBSERV-1803: Allow flow filtering for L4 protocols using two ports
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
Labels: lgtm, approved, jira/valid-reference

#764 Check version when discovering api
  pkg/discover/apis.go
Labels: lgtm, approved, no-qe, no-doc

#769 Fix podman builds
  Dockerfile
  Makefile
Labels: lgtm, approved, no-qe, no-doc

#768 NETOBSERV-1856: new role for metrics reading permissions
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constants/constants.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_reconciler.go
  pkg/loki/roles.go
  pkg/manager/manager.go
  pkg/resources/static_resources.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#778 NETOBSERV-1786: Automatically update bundle reference in the catalog
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  catalog/index.yaml
  hack/bundle_digest.sh
  hack/patch_catalog.py
  hack/update-build.sh
Labels: lgtm, approved, jira/valid-reference

#766 NETOBSERV-1848 Enable egress metric to show more traffic
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/flp/flp_controller_flowmetrics_test.go
  controllers/flp/flp_test.go
  controllers/flp/metrics_api_test.go
  docs/FlowCollector.md
  pkg/dashboards/dashboard_test.go
  pkg/metrics/predefined_metrics.go
Labels: lgtm, qe-approved, approved, ok-to-test

#733 NETOBSERV-1772: allow prom label remapping
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/samples/flowmetrics/dns_requests.yaml
  config/samples/flowmetrics/dns_responses.yaml
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowMetric.md
  go.mod
  go.sum
  pkg/helper/cardinality.go
  pkg/helper/helpers.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/golang.org/x/oauth2/LICENSE
  vendor/modules.txt
Labels: jira/valid-reference

#763 NETOBSERV-1811 set namespace ownership
  controllers/monitoring/monitoring_controller.go
  pkg/helper/client_helper.go
  pkg/helper/flowcollector.go
Labels: lgtm
