Repository netobserv/network-observability-operator, pull requests merged in 2024-12, with the labels that each got.

#917 Fix konflux build requirements
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/pipeline-bundle-ref.yaml
  .tekton/pipeline-fbc-ref.yaml
  .tekton/pipeline-ref.yaml
  requirements.txt
Labels: lgtm, approved

#919 Adding previous releases to fbc catalog
  .tekton/network-observability-operator-fbc-push.yaml
  catalog.Dockerfile.downstream
  catalog/index.yaml
  catalog/rc.yaml
  catalog/released/1.0.0.yaml
  catalog/released/1.1.1.yaml
  catalog/released/1.2.0.yaml
  catalog/released/1.3.0.yaml
  catalog/released/1.4.0.yaml
  catalog/released/1.4.1.yaml
  catalog/released/1.4.2.yaml
  catalog/released/1.5.0.yaml
  catalog/released/1.6.0.yaml
  catalog/released/1.6.1.yaml
  catalog/released/1.6.2.yaml
  catalog/released/1.7.0.yaml
  hack/patch_catalog.py
  hack/update-build.sh
Labels: lgtm, approved

#942 OLM forms, fix display name generation for mac
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  hack/crd2csvSpecDesc.sh
Labels: qe-approved

#863 NETOBSERV-1935: enable metrics from list/nested fields
  apis/flowcollector/v1beta1/flowcollector_webhook_test.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook_test.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/samples/flowmetrics/network-policies.yaml
  config/samples/flowmetrics/per-interface.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  docs/FlowMetric.md
  docs/Metrics.md
  pkg/dashboards/dashboard_test.go
  pkg/helper/helpers.go
  pkg/metrics/predefined_charts.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
Labels: qe-approved, approved, ok-to-test, jira/valid-reference

#943 update for new flags structure
  config/samples/flowmetrics/flows_with_flags_per_destination.yaml
  config/samples/flowmetrics/flows_with_flags_per_source.yaml
Labels: lgtm, approved

#819 NETOBSERV-1580: update frontend config for CLI
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, approved, jira/valid-reference

#944 Update container digest in bundle
  hack/container_digest.sh
Labels: lgtm, approved

#821 NETOBSERV-1965: packet translation feature support
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference
