Repository netobserv/network-observability-operator, pull requests merged in 2024-06, with the labels that each got.

#666 H&H: Allow using Test Console (standalone) from operator 🤘
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/constants/constants.go
  controllers/flowcollector_controller.go
  pkg/helper/flowcollector.go
Labels: lgtm, approved, no-qe, no-doc

#657 Regenerate docs
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  docs/FlowCollector.md
  docs/FlowMetric.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
  docs/flowmetric-flows-netobserv-io-v1alpha1.adoc
  docs/flows-format.adoc
  hack/asciidoc-gen-config.yaml
  hack/asciidoc-gen.sh
Labels: qe-approved

#665 NETOBSERV-1672: add cluster & zone to predefined metrics
  controllers/consoleplugin/consoleplugin_objects.go
  pkg/dashboards/dashboard_test.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
Labels: qe-approved, approved, ok-to-test, jira/valid-reference

#668 NETOBSERV-1672: add cluster & zone to predefined metrics (#665) [1.6 backport]
  controllers/consoleplugin/consoleplugin_objects.go
  pkg/dashboards/dashboard_test.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
Labels: qe-approved, approved, jira/valid-reference

#669 NETOBSERV-1647: Do not load loki cert when loki disabled
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#670 NETOBSERV-1647: Do not load loki cert when loki disabled [Backport 1.6]
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/patches/webhook_in_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#675 NETOBSERV-1688: relax ebpf drop alert [1.6 backport]
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent-metrics-test.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/agent_metrics.go
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
Labels: qe-approved, approved, ok-to-test, jira/valid-reference

#674 NETOBSERV-1688: relax ebpf drop alert
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent-metrics-test.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/agent_metrics.go
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
Labels: lgtm, qe-approved, approved, jira/valid-reference

#682 NETOBSERV-1707: move to go 1.22
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#683 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: lgtm

#677 NETOBSERV-1705: do not send zone/cluster labels config...
  controllers/consoleplugin/consoleplugin_objects.go
  pkg/dashboards/dashboard_test.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
  pkg/test/util/utils.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#689 force conflicts on deploy
  Makefile
Labels: lgtm, approved, no-qe, no-doc

#691 NETOBSERV-1617: generalize flow filter so it can be used with pcap feature
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, no-qe, ok-to-test, jira/valid-reference

#692 NETOBSERV-1731: hide metrics enable setting from form
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference
