Repository netobserv/network-observability-operator, pull requests merged in 2024-11, with the labels that each got.

#828 Align build steps - distinguish clean vs dev builds
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: lgtm, no-qe, no-doc

#830 NETOBSERV-1633 Konflux pipeline multiarch and downstream requirements
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
  .tekton/pipeline-bundle-ref.yaml
  .tekton/pipeline-fbc-ref.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
  bundle.Dockerfile.downstream
  catalog.Dockerfile.downstream
  hack/update-build.sh
  requirements.txt
Labels: lgtm, approved

#803 backport: NETOBSERV-1633 konflux backport
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
  .tekton/pipeline-bundle-ref.yaml
  .tekton/pipeline-fbc-ref.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
  bundle.Dockerfile.downstream
  catalog.Dockerfile.downstream
  hack/update-build.sh
  requirements.txt
Labels: lgtm, approved

#845 Update image reference to point to final repository
  hack/container_digest.sh
Labels: lgtm, approved

#847 Added missing rpms check task in konflux
  .tekton/network-observability-operator-1-7-push.yaml
  .tekton/network-observability-operator-bundle-1-7-push.yaml
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#820 NETOBSERV-1885: improve resource filter descriptions
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#853 Fixing bundle prodsec violations
  .tekton/pipeline-bundle-ref.yaml
  bundle.Dockerfile.downstream
  hack/patch_csv.py
Labels: lgtm, approved

#857 Fixing bundle build
  .tekton/pipeline-bundle-ref.yaml
Labels: lgtm, approved

#859 Add imageref in csv during bundle build
  bundle.Dockerfile.downstream
  hack/patch_csv.py
Labels: lgtm, approved

#860 Bumping images digest
  bundle.Dockerfile.downstream
  hack/container_digest.sh
Labels: lgtm, approved

#865 Bumping bundle digest in fbc configuration file
  hack/bundle_digest.sh
Labels: lgtm, approved

#861 update golangci-lint
  .golangci.yml
  Makefile
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_minimal_test.go
  controllers/flp/flp_controller_flowmetrics_test.go
  controllers/flp/flp_controller_test.go
  controllers/flp/suite_test.go
  controllers/monitoring/monitoring_controller_test.go
  controllers/monitoring/suite_test.go
  controllers/networkpolicy/np_controller_test.go
  controllers/networkpolicy/suite_test.go
  controllers/suite_test.go
  pkg/narrowcache/client.go
  pkg/watchers/watcher.go
  pkg/watchers/watcher_test.go
Labels: no-qe, no-doc

#867 Change rbac-proxy URL
  hack/patch_csv.py
Labels: lgtm, approved

#875 Konflux: fixing image source tagging
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#877 Bumping image digest in bundle
  hack/container_digest.sh
Labels: lgtm, approved

#878 Fix konflux results
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#835 Adapt columns in frontend config with changes in plugin
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, approved, no-qe, no-doc

#886 Bumping digests in bundle
  hack/container_digest.sh
Labels: lgtm, approved

#887 Bumping bundle digest in fbc
  hack/bundle_digest.sh
Labels: lgtm, approved

#895 Make base image for FBC configurable
  catalog.Dockerfile.downstream
Labels: lgtm, approved

#897 Add release history to fbc
  catalog/index.yaml
  catalog/rc.yaml
  catalog/released/1.0.0.yaml
  catalog/released/1.1.1.yaml
  catalog/released/1.2.0.yaml
  catalog/released/1.3.0.yaml
  catalog/released/1.4.0.yaml
  catalog/released/1.4.1.yaml
  catalog/released/1.4.2.yaml
  catalog/released/1.5.0.yaml
  catalog/released/1.6.0.yaml
  catalog/released/1.6.1.yaml
  catalog/released/1.6.2.yaml
  catalog/released/1.7.0.yaml
  hack/patch_catalog.py
  hack/update-build.sh
Labels: lgtm, approved

#898 Add latest tag to fbc
  .tekton/network-observability-operator-fbc-1-7-push.yaml
Labels: lgtm, approved

#591 NETOBSERV-1692: Add FLP-based filters & deduper options
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_pipeline_builder_test.go
  controllers/flp/flp_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/flowcollector.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_s3.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_filter.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/convert.go
  vendor/modules.txt
Labels: approved, jira/valid-reference

#833 NETOBSERV-1890: expand TCP flags as string in FLP
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/flp/flp_pipeline_builder.go
  go.mod
  go.sum
  pkg/helper/cardinality/cardinality.json
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/tcp_flags.go
  vendor/modules.txt
Labels: qe-approved, approved, jira/valid-reference
