Repository netobserv/network-observability-operator, pull requests merged in 2024-08, with the labels that each got.

#727 NETOBSERV-1746: Adapt health dashboard to flows metrics enabled
  controllers/monitoring/monitoring_controller.go
  controllers/monitoring/monitoring_objects.go
  pkg/dashboards/dashboard_test.go
  pkg/dashboards/health.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#690 NETOBSERV-1377: Add controller to deploy netobserv network policy
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/constants/constants.go
  controllers/controllers.go
  controllers/flowcollector_controller_iso_test.go
  controllers/networkpolicy/np_controller.go
  controllers/networkpolicy/np_controller_test.go
  controllers/networkpolicy/np_objects.go
  controllers/networkpolicy/np_test.go
  controllers/networkpolicy/suite_test.go
  controllers/reconcilers/reconcilers.go
  docs/FlowCollector.md
  pkg/manager/manager.go
  pkg/manager/status/status_manager.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#710 NETOBSERV-1755 Add filter for TCP flags
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test

#724 NETOBSERV-1777: Allow DNS tracking to use configurable port for tracking
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, no-qe, ok-to-test, jira/valid-reference, no-doc

#725 NETOBSERV-1758: fix error with monitoring ctrl w/o openshift
  controllers/monitoring/monitoring_controller.go
  pkg/test/envtest.go
  vendor/github.com/openshift/api/security/v1/zz_generated.crd-manifests/0000_03_config-operator_01_securitycontextconstraints.crd.yaml
  vendor/github.com/openshift/api/security/v1/zz_generated.crd-manifests/doc.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#728 NETOBSERV-1786: Add support to build file based catalog
  Makefile
  catalog.Dockerfile
  catalog/index.yaml
  hack/update_fbc.sh
Labels: lgtm, approved, jira/valid-reference

#736 Test console improvements
  .mk/development.mk
  FAQ.md
Labels: lgtm, approved, no-qe, no-doc

#749 Allow flow filtering for L4 protocols using two ports [BP to 1.6.2]
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
Labels: lgtm, approved

#750 [Backport] NETOBSERV-1779 allow port filtering if protocol not set
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved

#752 NETOBSERV-1806 ICMP type are showing as n/a for icmp traffic
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, qe-approved, approved, ok-to-test

#726 NETOBSERV-1689 Allow multi-tenant Prometheus queries
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/flp/flp_common_objects.go
Labels: lgtm, qe-approved, approved, ok-to-test

#753 NETOBSERV-1777: Allow DNS tracking to use configurable port for tracking [BP]
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, jira/valid-reference
