Repository netobserv/network-observability-operator, pull requests merged in 2024-04, with the labels that each got.

#559 NETOBSERV-1426: detect external workloads / openshift subnets
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/rbac/role.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_objects.go
  controllers/flp/flp_transfo_reconciler.go
  controllers/flp/metrics_api_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  pkg/helper/flowcollector.go
  pkg/manager/manager.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/modules.txt
Labels: qe-approved, approved, jira/valid-reference

#608 OCPBUGS-30191: typo omited->omitted
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe, jira/valid-reference, jira/invalid-bug

#605 Update controller-gen, improve kind deployment
  .mk/local.mk
  Makefile
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/rbac/role.yaml
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe, no-doc

#612 codecov v4
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#614 Sampling check
  controllers/ebpf/agent_controller.go
Labels: lgtm

#607 NETOBSERV-1478: Add eBPF Agent flows filtering capability
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#617 NETOBSERV-1605: add flow filter to ebpf agent dashboard
  pkg/dashboards/health.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#620 Codecov add env token from secret
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
Labels: lgtm, approved

#619 Enable openshift subnets by default
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flowmetrics/cluster_external_egress_traffic.yaml
  config/samples/flowmetrics/cluster_external_ingress_traffic.yaml
  config/samples/flowmetrics/pods_accept_outside.yaml
  config/samples/flowmetrics/pods_talking_outside.yaml
  controllers/consoleplugin/consoleplugin_test.go
  docs/FlowCollector.md
  pkg/helper/client_helper.go
  pkg/helper/flowcollector.go
Labels: no-qe, no-doc

#618 NETOBSERV-1606: Add PODs tolerations config to ebpf agent, flp and console plugin
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/flowcollector_webhook_test.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_common_objects.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#621 README / markdown updates
  FAQ.md
  README.md
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
Labels: lgtm, approved, no-qe, no-doc

#623 NETOBSERV-1610: document cardinality warning per field
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_test.go
  docs/flows-format.adoc
  hack/asciidoc-flows-gen.sh
  hack/flows-format-header.adoc
Labels: approved, jira/valid-reference

#622 NETOBSERV-1614: Metrics API validation webhook
  Makefile
  PROJECT
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook_test.go
  apis/flowmetrics/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/crd/kustomization.yaml
  config/openshift/patch.yaml
  config/webhook/manifests.yaml
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  main.go
  pkg/helper/helpers.go
  pkg/manager/manager.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#628 NETOBSERV-1619: use dedicated metrics ports for netobserv to avoid conflicts
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/constants/constants.go
  controllers/ebpf/agent-metrics-test.go
  controllers/ebpf/agent-metrics.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_test.go
  docs/FlowCollector.md
  pkg/helper/flowcollector.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#610 NETOBSERV-1427 Added support to FLP dynamic configmap
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller_flowmetrics_test.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_objects.go
  controllers/flp/flp_transfo_reconciler.go
  controllers/flp/metrics_api_test.go
  go.mod
  go.sum
  pkg/volumes/builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/pipeline_builder.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/kubernetes.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved

#633 NETOBSERV-1626: add configmaps to service account
  controllers/flp/flp_transfo_objects.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#632 NETOBSERV-1625: Add ebpf altering for flows drop
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/constants/constants.go
  controllers/ebpf/agent-metrics.go
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
Labels: lgtm, qe-approved, approved, jira/valid-reference
