Repository netobserv/network-observability-operator, pull requests merged in 2024-02, with the labels that each got.

#551 NETOBSERV-1214 & NETOBSERV-1399 Backport
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/constants/constants.go
  pkg/loki/labels.go
Labels: lgtm, approved

#554 NETOBSERV-1458: reduce loki streams, index FlowLayer
  controllers/constants/constants.go
  controllers/flp/flp_test.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#555 NETOBSERV-1458: reduce loki streams, index FlowInfra
  controllers/constants/constants.go
  controllers/flp/flp_test.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#550 Doc: regenerate API refs (FlowCollector + Flow Format)
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_test.go
  controllers/flowcollector_controller_certificates_test.go
  docs/FlowCollector.md
  docs/GeneratingAsciidocAPI.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
  docs/flows-format.adoc
  hack/asciidoc-flows-gen.sh
  hack/asciidoc-gen.sh
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  hack/flows-format-header.adoc
Labels: lgtm, approved

#553 image references file
  manifests/image-references
Labels: lgtm

#546 NETOBSERV-1214 & NETOBSERV-1399 Cluster name & zone features
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/constants/constants.go
  pkg/loki/labels.go
Labels: lgtm, approved, ok-to-test

#558 Fix envtests with FlowCollector deletion [1.5 backport]
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_minimal_test.go
  controllers/flowcollector_controller_test.go
  controllers/flp/flp_controller_flowmetrics_test.go
  controllers/flp/flp_controller_test.go
  controllers/flp/suite_test.go
  controllers/monitoring/monitoring_controller_test.go
  controllers/monitoring/suite_test.go
  controllers/suite_test.go
  pkg/manager/status/status_manager.go
  pkg/test/envtest.go
Labels: lgtm, approved

#563 Bump dependencies: gomega, apiserver, controller-runtime
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/zapr/.golangci.yaml
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/slogzapr.go
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/github.com/go-logr/zapr/zapr_noslog.go
  vendor/github.com/go-logr/zapr/zapr_slog.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/be_comparable_to_matcher.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/RELEASE.md
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/field/selector/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/syncs/syncs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/procattr_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/procattr_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
Labels: lgtm, approved

#564 Bump dependencies: gomega, apiserver, controller-runtime [Backport 1.5]
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/zapr/.golangci.yaml
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/slogzapr.go
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/github.com/go-logr/zapr/zapr_noslog.go
  vendor/github.com/go-logr/zapr/zapr_slog.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/be_comparable_to_matcher.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/RELEASE.md
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/field/selector/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/syncs/syncs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/procattr_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/procattr_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
Labels: lgtm, approved

#561 Update README
  README.md
Labels: lgtm, approved, no-qe, no-doc

#567 NETOBSERV-1470: Reduce memory usage in agent due to kafka batches
  README.md
  apis/flowcollector/v1alpha1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
Labels: lgtm, approved, jira/valid-reference

#566 NETOBSERV-1470: reduce memory usage in agent due to kafka batches [1.5 backport]
  README.md
  apis/flowcollector/v1alpha1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta1_flowcollector.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#568 doc feedback
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  docs/GeneratingAsciidocAPI.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
  docs/flows-format.adoc
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  hack/flows-format-header.adoc
Labels: lgtm, approved

#577 NETOBSERV-1513: Remove v1alpha1, deprecate v1beta1, store v1beta2
  DEVELOPMENT.md
  Makefile
  PROJECT
  apis/flowcollector/v1alpha1/doc.go
  apis/flowcollector/v1alpha1/flowcollector_types.go
  apis/flowcollector/v1alpha1/flowcollector_webhook.go
  apis/flowcollector/v1alpha1/groupversion_info.go
  apis/flowcollector/v1alpha1/zz_generated.conversion.go
  apis/flowcollector/v1alpha1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta1/doc.go
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/patches/webhook_in_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  config/samples/flows_v1alpha1_flowcollector.yaml
  config/samples/kustomization.yaml
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  hack/cloned.flows.netobserv.io_flowmetrics.yaml
  main.go
  pkg/test/envtest.go
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#580 NETOBSERV-1466 rely on duplicate different than 'true' for prom queries
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/samples/flows_v1alpha1_flowmetric.yaml
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/metrics_api_test.go
  go.mod
  go.sum
  pkg/conversion/conversion.go
  pkg/metrics/predefined_metrics.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/api.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_otlp.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/config/config.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, breaking-change

#581 bump FLP
  controllers/flp/metrics_api_test.go
  go.mod
  go.sum
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/encode_prom.go
  vendor/modules.txt
Labels: lgtm, approved
