Repository netobserv/network-observability-operator, pull requests merged in 2024-01, with the labels that each got.

#512 NETOBSERV-1430: make operator provide agent IP
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_certificates_test.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#524 NETOBSERV-1451: Bump ubi 9.3 / go 1.21
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#501 NETOBSERV-1298: Add netobserv operator changes to support dup list
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, jira/valid-reference

#523 NETOBSERV-1017: pods/services bandwidth (flowmetrics / dev preview)
  config/samples/flowmetrics/pods_incoming_bytes.yaml
  config/samples/flowmetrics/pods_outgoing_bytes.yaml
  config/samples/flowmetrics/services_incoming_bytes.yaml
Labels: lgtm, approved, no-qe, jira/valid-reference, no-doc

#467 NETOBSERV-1092 Move CRD fields to advanced
  Dockerfile
  apis/flowcollector/v1alpha1/flowcollector_types.go
  apis/flowcollector/v1alpha1/flowcollector_webhook.go
  apis/flowcollector/v1alpha1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/flowcollector_webhook_test.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
  controllers/flowcollector_controller_console_test.go
  controllers/flowcollector_controller_ebpf_test.go
  controllers/flowcollector_controller_iso_test.go
  controllers/flowcollector_controller_test.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller_test.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  controllers/ovs/flowsconfig_cno_reconciler.go
  controllers/ovs/flowsconfig_ovnk_reconciler.go
  docs/FlowCollector.md
  go.mod
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  main.go
  pkg/helper/crd.go
  pkg/helper/flowcollector.go
  pkg/helper/helpers_test.go
  pkg/helper/loki_config.go
  pkg/test/envtest.go
Labels: lgtm, approved, testing-breaking-change

#529 NETOBSERV-1407 - Loki labels for deduper merge
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/constants/constants.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  pkg/loki/labels.go
Labels: lgtm, approved, no-qe

#425 NETOBSERV-791 Better organize OLM form
  Makefile
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  hack/crd2csvSpecDesc.sh
Labels: lgtm, approved, ok-to-test

#535 swap-image-csv.sh updates and minor fixes to set-plugin-image
  .mk/development.mk
  hack/swap-image-csv.sh
Labels: lgtm, approved

#536 NETOBSERV-1308: security context enforcement
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_common_objects.go
  pkg/helper/security.go
Labels: lgtm, approved, jira/valid-reference

#537 NETOBSERV-1203 Add field to enable zone
  apis/flowcollector/v1alpha1/flowcollector_webhook.go
  apis/flowcollector/v1alpha1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/flowcollector_controller_iso_test.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  go.mod
  go.sum
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  hack/crd2csvSpecDesc.sh
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_network.go
  vendor/modules.txt
Labels: lgtm, approved

#539 bug fix to use OPERATOR_NS instead
  .mk/development.mk
Labels: lgtm, approved

#544 Fix flow layer name
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, no-qe, no-doc

#545 NETOBSERV-1203: minor adjustments
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  pkg/helper/flowcollector.go
  pkg/loki/labels.go
Labels: lgtm, jira/valid-reference

#547 NETOBSERV-1203: minor adjustments [backport 1.5]
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/flowcollector_webhook.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  controllers/ebpf/agent_controller.go
  controllers/flp/flp_pipeline_builder.go
  docs/FlowCollector.md
  hack/cloned.flows.netobserv.io_flowcollectors.yaml
  pkg/helper/flowcollector.go
  pkg/loki/labels.go
Labels: approved, jira/valid-reference

#548 Fix flow layer name [1.5 backport]
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: approved

#549 Try fixing flaky test
  controllers/flowcollector_controller.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flp/flp_controller.go
  controllers/monitoring/monitoring_controller.go
  pkg/manager/status/util.go
Labels: lgtm, approved
