Repository netobserv/network-observability-operator, pull requests merged in 2024-10, with the labels that each got.

#794 NETOBSERV-1633: Enable prefetch dependencies in konlfux build pipelines
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
Labels: lgtm, approved, jira/valid-reference

#798 NETOBSERV-1633: Fix operator konflux build violations
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
  hack/update-build.sh
Labels: lgtm, approved, jira/valid-reference

#799 NETOBSERV-1893: fix netobserv-mertics-reader role creation
  controllers/flp/flp_controller.go
  pkg/loki/roles.go
  pkg/resources/static_resources.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#800 NETOBSERV-1893: fix netobserv-mertics-reader role creation [1.7 backport]
  controllers/flp/flp_controller.go
  pkg/loki/roles.go
  pkg/resources/static_resources.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#806 NETOBSERV-1811 promote managed label
  controllers/monitoring/monitoring_controller.go
Labels: lgtm, approved, ok-to-test

#807 NETOBSERV-1811 followup backport
  controllers/monitoring/monitoring_controller.go
Labels: lgtm, qe-approved, approved, ok-to-test

#790 Add packet drop filtering API
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
Labels: lgtm, approved, ok-to-test

#812 Networkevents feature is DevPreview [1.7 backport]
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#811 Networkevents feature is DevPreview
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved

#816 NETOBSERV-1934: allow connection from apiserver
  controllers/constants/constants.go
  controllers/networkpolicy/np_objects.go
  main.go
Labels: lgtm, approved, jira/valid-reference

#813 NETOBSERV-1933: do not set default additional namespaces for netpol
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
Labels: lgtm, approved, no-qe, jira/valid-reference

#817 NETOBSERV-1931: introduce flowcollector validation webhook
  PROJECT
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
  apis/flowcollector/v1beta2/flowcollector_webhook.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook.go
  apis/flowmetrics/v1alpha1/flowmetric_webhook_test.go
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/agent_metrics.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_reconciler.go
  controllers/flp/metrics_api_test.go
  controllers/monitoring/monitoring_controller.go
  controllers/networkpolicy/np_objects.go
  controllers/networkpolicy/np_test.go
  controllers/reconcilers/common.go
  go.mod
  go.sum
  main.go
  pkg/cluster/cluster.go
  pkg/discover/apis.go
  pkg/discover/permissions.go
  pkg/manager/manager.go
  pkg/test/envtest.go
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference
