Repository netobserv/network-observability-operator, pull requests merged in 2025-01, with the labels that each got.

#982 Pkt translation envvar not been set correctly
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, ok-to-test

#950 Adding version label in downstream build
  Dockerfile.downstream
  bundle.Dockerfile.downstream
  catalog.Dockerfile.downstream
Labels: lgtm

#965 NETOBSERV-2048: Add webhook check to prevent CIDR duplication when configure multi rules filtering
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
Labels: lgtm, qe-approved, approved, jira/valid-reference

#998 make sure zone_id is visible when pkt xlation feature is enabled
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, approved

#1010 Health: show metrics cardinality
  pkg/dashboards/health.go
Labels: lgtm, approved

#1014 Adding lines in digest file to reduce conflicts
  hack/container_digest.sh
Labels: lgtm, approved

#1017 NETOBSERV-2055: remove xlatIcmpId
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#1022 Refresh archicture doc
  CONTRIBUTING.md
  docs/Architecture.md
  docs/assets/architecture-direct.png
  docs/assets/architecture-kafka.png
  docs/assets/frontend.png
Labels: lgtm, approved

#909 NETOBSERV-1904 add configs for UDNs
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/flp/flp_test.go
  pkg/helper/loki/labels_test.go
  pkg/helper/loki/loki-labels.json
Labels: lgtm, approved, no-qe

#991 NETOBSERV-1956: NETOBSERV-1957: webhook conntrack cases
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  docs/FlowCollector.md
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#1044 update webhook check for 4.18 features and pktDrop
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
Labels: lgtm, approved

#1045 Automatic UDN enrichment
  controllers/flp/flp_pipeline_builder.go
Labels: lgtm

#999 NETOBSERV-2010: manage cardinality for netevents nested labels (also NETOBSERV-2056)
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/flp/flp_controller_flowmetrics_test.go
  hack/asciidoc-flows-gen.sh
  pkg/helper/cardinality/cardinality.json
Labels: jira/valid-reference

#1059 update kind, remove bingo
  .bingo/.gitignore
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/bingo.sum
  .bingo/go.mod
  .bingo/kind.mod
  .bingo/kind.sum
  .bingo/variables.env
  .mk/local.mk
  Makefile
  config/kind/kind.config.yaml
Labels: lgtm, no-qe, no-doc

#1051 NETOBSERV-2075: [minor] Add agent severity to error metric
  pkg/dashboards/health.go
Labels: lgtm, no-qe, jira/valid-reference, no-doc

#1042 feat: Helm Charts created
  helm/netobserv/Chart.yaml
  helm/netobserv/templates/certificate.yaml
  helm/netobserv/templates/deployment.yaml
  helm/netobserv/templates/flows.netobserv.io_flowcollectors.yaml
  helm/netobserv/templates/flows.netobserv.io_flowmetrics.yaml
  helm/netobserv/templates/netobserv-manager-config_v1_configmap.yaml
  helm/netobserv/templates/netobserv-metrics-service_v1_service.yaml
  helm/netobserv/templates/netobserv-webhook-service_v1_service.yaml
  helm/netobserv/templates/roles.yaml
  helm/netobserv/values.yaml
Labels: lgtm, approved, no-qe, no-doc, needs-ok-to-test

#1068 Add missing peer map to bpfman volume
  controllers/ebpf/agent_controller.go
Labels: lgtm, approved, ok-to-test

#912 NETOBSERV-1981: Fix Exporters form view
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  docs/FlowCollector.md
Labels: lgtm, ok-to-test, jira/valid-reference

#1075 Fixe typo in bundle images digests
  hack/container_digest.sh
Labels: lgtm
