Repository netobserv/network-observability-operator, pull requests merged in 2025-08, with the labels that each got.

#1788 Allow removing loki labels via advanced config
  api/flowcollector/v1beta2/flowcollector_types.go
  api/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  helm/crds/flows.netobserv.io_flowcollectors.yaml
  internal/controller/consoleplugin/consoleplugin_objects.go
  internal/controller/flp/flp_pipeline_builder.go
  internal/controller/flp/flp_test.go
  internal/pkg/helper/loki/labels.go
  internal/pkg/helper/loki/labels_test.go
  internal/pkg/helper/loki/loki-labels.json
Labels: lgtm, needs-review

#1731 NETOBSERV-2294: Adding egress support to network policy
  internal/controller/constants/constants.go
  internal/controller/networkpolicy/np_objects.go
  internal/controller/networkpolicy/np_test.go
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#1878 Fix doc link to net obs operator installation
  config/descriptions/ocp.md
Labels: lgtm, approved, ok-to-test
