Repository netobserv/network-observability-operator, pull requests merged in 2025-09, with the labels that each got.

#1915 added support of Node Affinity and custom cluster domain
  hack/helm-update.sh
  helm/templates/certificate.yaml
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: needs-ok-to-test

#1987 deploy csv from makefile
  Makefile
Labels: lgtm

#1990 chore(KONFLUX-6210): fix and set name and cpe label for network-observability-operator-bundle-zstream
  Dockerfile-args.downstream
  Dockerfile.downstream
  bundle.Dockerfile
  bundle.Dockerfile.downstream
Labels: needs-ok-to-test

#1996 NETOBSERV-2355: Rename sampling ratio/rate -> interval
  FAQ.md
  api/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
  docs/FlowCollector.md
  helm/crds/flows.netobserv.io_flowcollectors.yaml
  internal/controller/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, jira/valid-reference, needs-review

#2036 Fix upstream deploy/bundle issues with PF4 image
  Makefile
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm

#2043 Improve bundle clean message
  .github/workflows/pull_request.yml
Labels: lgtm

#1988 NETOBSERV-2405: fix missing subnet labels from otel
  internal/pkg/helper/otel/otel-config.json
  internal/pkg/helper/otel/otel_config_test.go
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#2020 Regenerate docs
  api/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
  docs/flowmetric-flows-netobserv-io-v1alpha1.adoc
  docs/flows-format.adoc
  hack/asciidoc-flows-gen.sh
  helm/crds/flows.netobserv.io_flowcollectors.yaml
Labels: lgtm
