Repository netobserv/network-observability-operator, pull requests merged in 2025-03, with the labels that each got.

#1210 Add QE team approvers on nudging PRs
  .tekton/fbc-v-4-12-push.yaml
  .tekton/fbc-v4-14-push.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-push.yaml
  .tekton/fbc-v4-18-push.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-push.yaml
  hack/nudging/OWNERS
  hack/nudging/bundle_digest.sh
  hack/nudging/container_digest.sh
  hack/update-build.sh
Labels: lgtm

#1208 RELEASE BLOCKER(March 17, 2025): Add fbc-target-index-pruning-check to FBC pipelines
  .tekton/pipeline-fbc-ref.yaml
Labels: ok-to-test

#1220 Improve helm chart
  .mk/development.mk
  Makefile
  README.md
  config/kind/deployment-prometheus.yaml
  helm/Chart.yaml
  helm/LICENSE
  helm/README.md
Labels: lgtm

#1209 Refactor roles: static definitions in bundle
  Makefile
  bundle/manifests/netobserv-config-watcher_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/netobserv-expose-metrics_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-hostnetwork_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-informers_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-loki-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-loki-writer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  bundle/manifests/netobserv-token-review_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/component_roles.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_reconciler.go
  controllers/constants/constants.go
  controllers/ebpf/internal/permissions/permissions.go
  controllers/flowcollector_controller_certificates_test.go
  controllers/flowcollector_controller_console_test.go
  controllers/flp/flp_common_objects.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_controller_test.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_pipeline_builder_test.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_objects.go
  controllers/flp/flp_transfo_reconciler.go
  controllers/flp/metrics_api_test.go
  controllers/monitoring/monitoring_controller.go
  controllers/monitoring/monitoring_objects.go
  controllers/reconcilers/common.go
  controllers/reconcilers/namespaced_objects_manager.go
  controllers/reconcilers/reconcilers.go
  helm/templates/clusterrole.yaml
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/helper/flowcollector.go
  pkg/helper/loki/roles.go
  pkg/manager/manager.go
  pkg/resources/roles.go
  pkg/resources/static_resources.go
  pkg/test/kube_mock.go
Labels: lgtm, approved, ok-to-test

#1232 NETOBSERV-2108: fix upstream catalog generation
  Makefile
  bundle.Dockerfile.downstream
  catalog.Dockerfile
  catalog.Dockerfile.downstream
  catalog/index.yaml
  catalog/rc.yaml
  catalog/released-legacy/bundles.yaml
  catalog/released-legacy/index.yaml
  catalog/released-legacy/other.yaml
  catalog/released/1.0.0.yaml
  catalog/released/1.1.1.yaml
  catalog/released/1.2.0.yaml
  catalog/released/1.3.0.yaml
  catalog/released/1.4.0.yaml
  catalog/released/1.4.1.yaml
  catalog/released/1.4.2.yaml
  catalog/released/1.5.0.yaml
  catalog/released/1.6.0.yaml
  catalog/released/1.6.1.yaml
  catalog/released/1.6.2.yaml
  catalog/released/bundles.yaml
  catalog/released/index.yaml
  catalog/released/other.yaml
  catalog/unreleased-legacy/next/bundle.yaml
  catalog/unreleased-legacy/next/index.yaml
  catalog/unreleased/next/bundle.yaml
  catalog/unreleased/next/index.yaml
  hack/patch_catalog.py
  hack/refresh-redhat-catalog.sh
  hack/update-build.sh
  hack/update_fbc.sh
Labels: qe-approved, ok-to-test, jira/valid-reference

#1096 NETOBSERV-1955: fix wrong metrics for conversation tracking
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  docs/FlowCollector.md
  helm/templates/flows.netobserv.io_flowcollectors.yaml
  pkg/metrics/predefined_metrics.go
Labels: qe-approved, jira/valid-reference

#1238 Fix: config-watcher must be a ClusterRole
  bundle/manifests/netobserv-config-watcher_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/component_roles.yaml
  controllers/flp/flp_monolith_reconciler.go
  controllers/flp/flp_transfo_reconciler.go
  pkg/resources/roles.go
Labels: lgtm, qe-approved, ok-to-test

#1236 README: discussions and contributions
  README.md
Labels: lgtm, no-qe, no-doc

#1258 NETOBSERV-2185: fix loki writer role name
  controllers/constants/constants.go
  controllers/flp/flp_controller_test.go
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#1237 NETOBSERV-2150: add license to downstream container
  Dockerfile.downstream
Labels: approved, no-qe, jira/valid-reference, no-doc

#1263 Downstream dockerfiles: manage BUILDVERSION, and some cleanup
  .tekton/network-observability-operator-bundle-pull-request.yaml
  .tekton/network-observability-operator-bundle-push.yaml
  .tekton/network-observability-operator-fbc-pull-request.yaml
  .tekton/network-observability-operator-fbc-push.yaml
  .tekton/network-observability-operator-pull-request.yaml
  .tekton/network-observability-operator-push.yaml
  .tekton/pipeline-bundle-ref.yaml
  .tekton/pipeline-fbc-ref.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile-args.downstream
  Dockerfile.downstream
  bundle.Dockerfile.downstream
  catalog.Dockerfile.downstream
  hack/patch_catalog.py
  hack/patch_csv.py
  hack/update-build.sh
Labels: lgtm

#1257 NETOBSERV-2174: check if LokiStack exists
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  helm/templates/clusterrole.yaml
  main.go
  pkg/manager/manager.go
  pkg/manager/status/status_manager.go
  pkg/test/envtest.go
  vendor/github.com/grafana/loki/operator/apis/loki/LICENSE
  vendor/github.com/grafana/loki/operator/apis/loki/v1/alertingrule_types.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/doc.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/groupversion_info.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/lokistack_types.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/recordingrule_types.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/rulerconfig_types.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/v1.go
  vendor/github.com/grafana/loki/operator/apis/loki/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: qe-approved, ok-to-test, jira/valid-reference

#1233 Tagging last konflux bundle as latest
  .tekton/network-observability-operator-bundle-push.yaml
Labels: approved

#1272 Fix downstream test catalog
  hack/patch_csv.py
  hack/update-build.sh
Labels: lgtm

#1273 Updating containers digests references
  hack/nudging/container_digest.sh
Labels: lgtm

#1290 NETOBSERV-2190: fix openshift version check with nightly builds
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
  pkg/cluster/cluster.go
Labels: lgtm, qe-approved, approved, ok-to-test, jira/valid-reference

#1298 NETOBSERV-2194:: use OCP4.19 version check for networkEvents/UDN/ebpfMgr
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
Labels: lgtm, approved, jira/valid-reference

#1287 nit: Add artifacthub badge and annotations
  README.md
  helm/Chart.yaml
  helm/README.md
Labels: lgtm
