Repository netobserv/network-observability-operator, pull requests merged in 2025-05, with the labels that each got.

#1434 NETOBSERV-2187: Replace filter API with a query expression language
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/samples/flows_v1beta2_flowcollector.yaml
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_pipeline_builder_test.go
  docs/FlowCollector.md
  go.mod
  go.sum
  helm/templates/flows.netobserv.io_flowcollectors.yaml
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_filter.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/dsl/eval.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/dsl/expr.y
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/dsl/expr.y.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/dsl/lexer.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/utils/filters/filters.go
  vendor/modules.txt
Labels: qe-approved, breaking-change, jira/valid-reference

#1483 CRD doc: update feature statuses
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  controllers/ebpf/internal/permissions/permissions.go
  docs/FlowCollector.md
  helm/templates/flows.netobserv.io_flowcollectors.yaml
Labels: lgtm

#1482 NETOBSERV-2186: configure sampling field name in FLP, refined sampling metrics
  apis/flowcollector/v1beta1/flowcollector_webhook_test.go
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  controllers/flp/flp_pipeline_builder.go
  controllers/flp/flp_test.go
  docs/FlowMetric.md
  go.mod
  go.sum
  helm/templates/flows.netobserv.io_flowmetrics.yaml
  pkg/dashboards/health.go
  pkg/metrics/predefined_metrics.go
  pkg/metrics/predefined_metrics_test.go
  vendor/github.com/netobserv/flowlogs-pipeline/pkg/api/transform_filter.go
  vendor/modules.txt
Labels: qe-approved, jira/valid-reference

#1409 Add operator to "Observability" category in OperatorHub
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  catalog/released/bundles.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
Labels: lgtm

#1508 NETOBSERV-2227: plugin feature "multiNetworks", and promote NetworkName columns
  bundle/manifests/netobserv-informers_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/rbac/component_roles.yaml
  config/rbac/role.yaml
  controllers/consoleplugin/config/config.go
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  helm/templates/clusterrole.yaml
  pkg/helper/flowcollector.go
  pkg/manager/manager.go
Labels: qe-approved, ok-to-test, jira/valid-reference, needs-review

#1519 Manage console pf4 builds
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/consoleplugin/consoleplugin_objects.go
  controllers/consoleplugin/consoleplugin_test.go
  controllers/constants/constants.go
  controllers/ebpf/agent_controller.go
  controllers/ebpf/bpfmanager-controller.go
  controllers/flowcollector_controller.go
  controllers/flp/flp_controller.go
  controllers/flp/flp_monolith_objects.go
  controllers/flp/flp_test.go
  controllers/flp/flp_transfo_objects.go
  controllers/flp/metrics_api_test.go
  controllers/reconcilers/common.go
  docs/Konflux.md
  hack/nudging/container_digest.sh
  hack/patch_csv.py
  helm/templates/deployment.yaml
  main.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/manager/config.go
Labels: needs-review

#1556 NETOBSERV-2222: single column ipsec status
  controllers/consoleplugin/config/static-frontend-config.yaml
Labels: lgtm, ok-to-test, jira/valid-reference
