Repository netobserv/network-observability-operator, pull requests merged in 2025-02, with the labels that each got.

#1108 release-1.8 Konflux bump bundle
  hack/container_digest.sh
Labels: lgtm, approved

#1132 Label konflux PRs as dependency
  .github/workflows/pr-labels.yaml
Labels: lgtm, approved

#1126 Regenerate doc [1.8 backport]
  Makefile
  RELEASE.md
  apis/flowcollector/v1beta1/flowcollector_types.go
  apis/flowcollector/v1beta1/zz_generated.conversion.go
  apis/flowcollector/v1beta1/zz_generated.deepcopy.go
  apis/flowcollector/v1beta2/flowcollector_types.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook.go
  apis/flowcollector/v1beta2/flowcollector_validation_webhook_test.go
  apis/flowcollector/v1beta2/zz_generated.deepcopy.go
  apis/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowcollectors.yaml
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/crd/bases/flows.netobserv.io_flowcollectors.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  config/descriptions/ocp.md
  config/descriptions/upstream.md
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  controllers/consoleplugin/config/static-frontend-config.yaml
  controllers/ebpf/agent_controller.go
  docs/FlowCollector.md
  docs/FlowMetric.md
  docs/flowcollector-flows-netobserv-io-v1beta2.adoc
  docs/flowmetric-flows-netobserv-io-v1alpha1.adoc
  docs/flows-format.adoc
  hack/asciidoc-flows-gen.sh
  pkg/helper/cardinality/cardinality.json
Labels: lgtm

#1136 FIPS compliance
  Dockerfile.downstream
Labels: lgtm, approved

#1140 Removing preflight check for bundle which is skipped for bundle
  .tekton/pipeline-bundle-ref.yaml
Labels: lgtm, approved

#1178 Uniform FBC definitions
  .tekton/fbc-v-4-12-push.yaml
  .tekton/fbc-v4-17-push.yaml
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
Labels: lgtm

#1177 Prepare 1.8 fbc
  hack/bundle_digest.sh
  hack/container_digest.sh
Labels: lgtm

#1181 Konflux: pinning validate-fbc task in konflux
  .tekton/pipeline-fbc-ref.yaml
Labels: lgtm

#1182 Use brew build for 4.18 catalog
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
Labels: lgtm

#1183 Konflux: Removing sbom task which as been deprecated
  .tekton/pipeline-fbc-ref.yaml
Labels: lgtm

#1202 fix catalog related images
  catalog/rc.yaml
  hack/patch_catalog.py
Labels: lgtm

#1198 NETOBSERV-2132: Regenerate catalog for legacy ocp
  Makefile
  catalog/index.yaml
  catalog/rc.yaml
  catalog/released/1.0.0.yaml
  catalog/released/1.1.1.yaml
  catalog/released/1.2.0.yaml
  catalog/released/1.3.0.yaml
  catalog/released/1.4.0.yaml
  catalog/released/1.4.1.yaml
  catalog/released/1.4.2.yaml
  catalog/released/1.5.0.yaml
  catalog/released/1.6.0.yaml
  catalog/released/1.6.1.yaml
  catalog/released/1.6.2.yaml
  catalog/released/1.7.0.yaml
  catalog/released_catalog.yaml
  hack/update_fbc.sh
Labels: jira/valid-reference
