Repository netobserv/network-observability-operator, pull requests merged in 2025-07, with the labels that each got.

#1645 NETOBSERV-2286: automatic metric naming after resource name
  api/flowmetrics/v1alpha1/flowmetric_types.go
  bundle/manifests/flows.netobserv.io_flowmetrics.yaml
  config/crd/bases/flows.netobserv.io_flowmetrics.yaml
  docs/FlowMetric.md
  helm/crds/flows.netobserv.io_flowmetrics.yaml
  internal/controller/flp/flp_pipeline_builder.go
  internal/controller/flp/flp_pipeline_builder_test.go
  internal/controller/flp/flp_test.go
  internal/controller/flp/fmstatus/flowmetrics_status.go
  internal/pkg/helper/helpers.go
  internal/pkg/helper/helpers_test.go
Labels: qe-approved, ok-to-test, jira/valid-reference

#1740 Fix .ci-operator base image
  .ci-operator.yaml
Labels: lgtm

#1739 [Trivial] Use faster way to get metrics cardinality
  internal/controller/constants/constants.go
  internal/controller/ebpf/agent_controller.go
  internal/controller/ebpf/agent_metrics.go
  internal/controller/flp/flp_monolith_objects.go
  internal/controller/flp/flp_monolith_reconciler.go
  internal/controller/flp/flp_transfo_objects.go
  internal/controller/flp/flp_transfo_reconciler.go
  internal/pkg/dashboards/health.go
Labels: lgtm, needs-review

#1746 Remove now unused 'replaces' csv field, and re-use BUILDVERSION when …
  Makefile
  bundle/manifests/netobserv-operator.clusterserviceversion.yaml
  config/csv/bases/netobserv-operator.clusterserviceversion.yaml
  hack/patch_csv.py
  hack/update-build.sh
Labels: needs-review

#1789 NETOBSERV-2225 - Deploy static plugin at operator startup - fix
  internal/controller/monitoring/monitoring_controller.go
  internal/pkg/helper/flowcollector.go
Labels: lgtm, qe-approved, approved
